### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by gokeson** [ammaraziz/ctgap#3]
at some point, we may want to 

- [ ] reconfigure scrubby to keep chlamydia reads only 
- [ ] remove bbnorm as shovill can downsample
- [ ] collate all assembled genomes, genotype and coverage outputs into a folder each when working with multiple samples.

**Comment by ammaraziz** [comment]
Combined with #2
